### ISSUE TITLE
 Few-Shot Learning dataset

### ISSUE THREAD

**Issue by RaptorMai** [JieShibo/PETL-ViT#10]
Hi, thanks again for your code. I am curious if you have the plan to release the data preparation code for few-shot learning for FGVC-Aircraft, Oxford-Pets, Food 101, Stanford Card and Oxford Flower.

**Comment by JieShibo** [comment]
Hi @RaptorMai,
Please refer to https://github.com/ZhangYuanhan-AI/NOAH/#data-preparation and https://github.com/ZhangYuanhan-AI/NOAH/blob/main/lib/datasets.py for few-shot datasets.
