### ISSUE TITLE
Few-shot results

### ISSUE THREAD

**Issue by heekhero** [JieShibo/PETL-ViT#11]
Hi, great work! Could you please provide me with the exact numbers of results in Fig.6 in terms of FacT-TT (61K), so I can use it to check the reproducibility and compare with my research.
Looking forward to hearing from you.

**Comment by JieShibo** [comment]
Hi @heekhero , 

-- | Food101 | StanfordCars | Flowers102 | FGVCAircraft | OxfordPets
-- | -- | -- | -- | -- | --
NOAH-1 shot | 31.8 | 7.3 | 88.1 | 8.2 | 69.7
 NOAH-2 shot  | 51.6 | 13.2 | 96.9 | 13.5 | 78.1
NOAH-4  shot  | 63.8 | 25.5 | 98.1 | 23.1 | 84.9
NOAH-8 shot   | 71.5 | 46.2 | 99.4 | 34.0 | 88.0
NOAH-16 shot  | 76.3 | 68.6 | 99.5 | 49.1 | 89.0
VPT-1 shot | 23.5 | 5.5 | 58.8 | 6.4 | 56.8
 VPT-2 shot  | 46.7 | 9.6 | 95.4 | 11.2 | 66.1
VPT-4 shot | 60.6 | 20.7 | 98.0 | 19.0 | 85.3
VPT-8  shot | 67.8 | 33.5 | 99.2 | 28.9 | 88.6
VPT-16 shot  | 72.6 | 56.0 | 99.4 | 42.5 | 89.6
  Lora-1 shot | 31.8 | 6.7 | 88.5 | 9.0 | 68.6 
  Lora-2 shot   | 48.7 | 13.5 | 96.4 | 13.5 | 76.1
  Lora-4 shot  | 59.0 | 26.4 | 98.1 | 22.1 | 85.7
  Lora-8 shot   | 66.4 | 45.9 | 99.1 | 34.6 | 87.3
  Lora-16 shot  | 72.5 | 68.2 | 99.6 | 47.6 | 88.7
Adapter-1 shot | 31.4 | 7.5 | 88.6 | 9.1 | 68.0
Adapter-2 shot  | 49.0 | 13.4 | 96.3 | 13.3 | 76.3
 Adapter-4 shot | 59.8 | 23.7 | 98.1 | 21.1 | 85.8
Adapter-8 shot  | 66.8 | 39.9 | 99.2 | 32.0 | 88.2
Adapter-16 shot  | 71.7 | 60.4 | 99.5 | 45.2 | 89.1
AdapterFormer-1 shot | 31.6 | 6.7 | 90.1 | 9.6 | 62.6
AdapterFormer-2 shot  | 48.2 | 13.2 | 96.4 | 13.2 | 74.7
 AdapterFormer-4 shot | 59.3 | 26.5 | 97.7 | 21.7 | 83.6
AdapterFormer-8 shot  | 67 | 46.6 | 99.0 | 33.9 | 87.2
AdapterFormer-16 shot  | 72.4 | 66.1 | 99.4 | 48.5 | 88.8
FacT-1 shot | 34.17 | 8.33 | 91.61 | 11.06 | 73.97
FacT-2 shot  | 54.00 | 15.44 | 96.95 | 15.50 | 81.54
 FacT-4 shot | 64.34 | 29.49 | 98.44 | 24.14 | 87.14
FacT-8 shot  | 71.29 | 52.18 | 99.4 | 36.76 | 89.22
FacT-16 shot  | 75.85 | 72.06 | 99.69 | 50.98 | 89.84

Note that the results of Flowers102 in the arxiv paper are out of date. Please refer to the table above.

**Comment by heekhero** [comment]
Thank you for sharing the results!

**Comment by Lucenova** [comment]
@JieShibo Hello, it's a great work. I have two question about FGVC dataset.
1. As we known, NOAH split FGVC by different seed. So the result that in above table is average result ?
2. I test the TT-16 in FGVC dataset, I find the result when scale is 100 be very terrible, I am not sure is that correct ?
