### ISSUE TITLE
About the weight initialization for the 'adapter_conv' in Convpass

### ISSUE THREAD

**Issue by Harry-zzh** [JieShibo/PETL-ViT#13]
Thank you for your outstanding work! Regarding the weight initialization method for the 'adapter_conv' in Convpass, some datasets are initialized using Xavier Uniform initialization, while others are not. I would like to inquire whether the different weight initialization methods for different datasets were determined through experiment results or if there is a specific rationale for the selection.
Looking forward to your reply. Thanks!

**Comment by JieShibo** [comment]
The weight initialization methods for different datasets were determined through experiment results.
