### ISSUE TITLE
Question about the performance of VTAB-1K with FacT

### ISSUE THREAD

**Issue by Bazinga699** [JieShibo/PETL-ViT#15]
Hello, inspiring work! I've encountered some issues while reproducing the results of FacT. Specifically, I'm having trouble replicating the results from the VTB-1k dataset using the default settings provided in the source code. I was wondering if you could kindly provide the detailed hyperparameter settings used for the different results presented in the paper.

|Dataset|Method|Paper|Reproduce|
|---| --- | --- | --- |
|VTAB-1K-average|FacT-TT<sub>4</sub>|73.5|-|
|VTAB-1K-average|FacT-TT<sub><=16</sub>|75.3|73.1|
|VTAB-1K-average|FacT-TK<sub>8</sub>|74.0|-|
|VTAB-1K-average|FacT-TK<sub><=32</sub>|75.6|73.0|

**Comment by JieShibo** [comment]
Can I have a look at the reproduced results on each dataset?

**Comment by Bazinga699** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/L/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/L/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Dataset | FacT-TT<=16 | FacT-TK<=32
-- | -- | --
caltech101 | 91.83 | 91.73
cifar | 71.07 | 71.28
clevr_count | 82.69 | 81.25
clevr_dist | 67.80 | 66.30
diabetic_retinopathy | 73.97 | 75.80
dmlab | 50.80 | 51.20
dsprites_loc | 80.18 | 82.51
dsprites_ori | 48.97 | 47.50
dtd | 70.85 | 70.59
eurosat | 95.70 | 95.81
kitti | 79.32 | 79.04
oxford_flowers102 | 99.07 | 99.14
oxford_iiit_pet | 90.41 | 90.27
patch_camelyon | 83.56 | 83.54
resisc45 | 84.11 | 85.17
smallnorb_azi | 34.72 | 33.83
smallnorb_ele | 40.22 | 39.37
sun397 | 54.68 | 54.29
svhn | 89.07 | 89.19
avg | 73.11 | 73.04



</body>

</html>


> Can I have a look at the reproduced results on each dataset?

**Comment by JieShibo** [comment]
Following NOAH, the "avg result" in our paper denotes "(Natural avg + Specialized avg + Structured avg) / 3". 
So the reproduced avg results should be 75.3 for FacT-TT and 75.4 for FacT-TK.

**Comment by Bazinga699** [comment]
> Following NOAH, the "avg result" in our paper denotes "(Natural avg + Specialized avg + Structured avg) / 3". So the reproduced avg results should be 75.3 for FacT-TT and 75.4 for FacT-TK.

Got it! Thanks
