### ISSUE TITLE
The number of trainable parameters

### ISSUE THREAD

**Issue by Zhangwenyao1** [JieShibo/PETL-ViT#2]
I want to know why the number of parameter is 2L ×( (2h + 1)d + 9h*h + 2h)? ( especially (2h+1)*d and 2h.)

**Comment by JieShibo** [comment]
Hi Wenyao,
1×1 Conv weight: d × h × 1 × 1, bias: h
3×3 Conv weight: h × h × 3 × 3, bias: h
1×1 Conv weight: h × d × 1 × 1 , bias: d
2 Convpass modules per layer
So there are 2L((2h + 1)d + 9h^2 + 2h) in total.
