### ISSUE TITLE
Could you please share the code for other baseline methods

### ISSUE THREAD

**Issue by Pang-Yatian** [JieShibo/PETL-ViT#5]
Hi Shibo,

Thanks for your great work. Your code is concise and easy to understand.

So may I ask if it is possible for sharing other baseline implementation codes, such as LoRA? It will help me a lot.

**Comment by Pang-Yatian** [comment]
I will refer to NOAH if you did not implement them by yourself. Thanks.

**Comment by JieShibo** [comment]
Hi Yatian,
I recommend reproducing the results of baselines with the code of NOAH, which is better organized. Our experimental setting (batch size, lr, wd, epoch,  etc.) is exactly the same as theirs.

**Comment by Pang-Yatian** [comment]
Thank you~
