### ISSUE TITLE
A question for the architecture

### ISSUE THREAD

**Issue by YuchenLiu98** [JieShibo/PETL-ViT#6]
Thanks for your great job. I want to make sure that the proposed adaptor is only added to every block of ViT (not position embedding layer). When I print the model, it is like 
![image](https://user-images.githubusercontent.com/108775627/187821880-9ffbc3e7-3d93-4be9-91d6-669cba818e2f.png)
Am I right? Since I use different versions of timm, I just want to make sure. Thanks a lot for your help.

**Comment by JieShibo** [comment]
Yes, you are right.
