### ISSUE TITLE
Question about  the reported performance.

### ISSUE THREAD

**Issue by luogen1996** [JieShibo/PETL-ViT#7]
I can not reproduce the reported performance in my machine. On 3090, i get average performance of 74.72 for convpass_attn. I also notice that the performance varies in different environments. For examlpe, the performance of cifar is 71.46  and 71.24 on 3090 and A100, respectively.

**Comment by JieShibo** [comment]
Hi,
The reported results in the paper are produced on RTX 3090. I wonder what script you ran to reproduce the results.

I'm not sure if different GPUs produce different results. We reran the code on different machines with RTX 3090 and got the same results.

**Comment by luogen1996** [comment]
> Hi, The reported results in the paper are produced on RTX 3090. I wonder what script you ran to reproduce the results.
> 
> I'm not sure if different GPUs produce different results. We reran the code on different machines with RTX 3090 and got the same results.

Thanks，now I obtain the reported results.
